### ISSUE TITLE
Błędne nazewnictwo w przelewach paynow

### ISSUE THREAD

**Issue by JacekBakowskiEMV** [pay-now/paynow-prestashop#101]
W przelewach z paynow brak informacji o numerze zamówienia.
W zamian tego pojawia się informacja o nr koszyka, w poprzednich wersjach był poprawny nr zamówienia.

np:
Numer zamówienia : 446_61b31809044a4
Opis zamówienia : Zamówienie do koszyka: 446

**Comment by emilleszczak2** [comment]
@JacekBakowskiEMV to nie jest błąd. Jest to celowy zabieg aby można było wykonać płatność przed zamówieniem w modelu White Label i obsłużyć błędy podawanego kodu BLIK.
Ta  zmiana zachowania jest tylko dla płatności BLIKIEM w modelu White Label.

**Comment by JacekBakowskiEMV** [comment]
A czy nie można dodać nr zamówienia w tym modelu , było by łatwiej zidentyfikować przelew i rozliczać zwroty po nr zamówienia.

p.s
Miałem włączoną poniższą opcje ale nic oprócz Numer zamówienia : 446_61b31809044a4 nie otrzymałem ?

"Włącz przesyłanie informacji o zamówionych produktach: nazwa, kategorie, ilość oraz cena. "

**Comment by emilleszczak2** [comment]
@JacekBakowskiEMV Nie można dodać tam numeru zamówienie którego jeszcze nie ma w Prestashop. Zamówienie fizycznie w sklepie jest tworzone po pozytywnej rejestracji transakcji.

Możesz sobie dokonać zmiany wtyczki w tym obszarze i np dodać wprowadzić tam adres mailowy kupującego.

Daj znać jaki przypadek zwrotów chcesz w ten sposób rozwiązać? Zwroty można zlecać z poziomu Prestashop i zostaną one dowiązane do płatności/zamówienia.

**Comment by Sasni** [comment]
Nie wystarczyło by zrobić tak, aby zamówienie tworzyło się na etapie przyciskania "złóż zamówienie" (co zostało chyba wykonane w wersji 1.6) - wtedy można by przekazywać dalej numer zamówienia jak chce Pan @JacekBakowskiEMV

**Comment by emilleszczak2** [comment]
@Sasni W przypadku płatności BLIKIEM zamówienie nigdy nie tworzy się przed płatnością. Tworzy się po zleceniu płatności lub po udanej płatności - to zostało dodane w 1.6.
