### ISSUE TITLE
Brak zmiany statusu na "zaksięgowane"

### ISSUE THREAD

**Issue by maskopatol69** [pay-now/paynow-prestashop#106]
Po aktualizacji do 1.6, moduł nie aktualizował statusów dla płatności przyjętych.
Po wgraniu 1.55 działa poprawnie oraz zaktualizował statusy dla tych zamówień złożonych w wersji 1.6, chociaż jeszcze nie dla wszystkich. 

Czy w wersji 1.6 zmieniły się np. linki z potwierdzeniem statusu płatności?

**Comment by emilleszczak2** [comment]
@maskopatol69 czy chodzi Tobie o powiadomienia o statusie płatności czy jakiś inny link ?

**Comment by maskopatol69** [comment]
Tak, dokładnie. 
W przypadku prestashop w ustawieniach Paynow mam:
module/paynow/return
module/paynow/notifications

Po aktualizacji wtyczki wszystkie zamówienia zatrzymywały się na statusie oczekiwania na płatność. Przez 40 min. nie zmieniał się status na żadnym z nich, mimo że w panelu Paynow płatności miały status przyjętych.

Wykonałem donwgrade modułu do wersji 1.55 i zaczęło działać prawidłowo + zmieniło statusy na tych zamówieniach składanych na wersji 1.6 (zmieniło na wszystkich).

**Comment by emilleszczak2** [comment]
@maskopatol69 znalazłem powód. zaraz będzie fix w nowej wersji

**Comment by emilleszczak2** [comment]
@maskopatol69 Możesz pobrać poprawioną wersję https://github.com/pay-now/paynow-prestashop/releases/tag/1.6.1

**Comment by maskopatol69** [comment]
Ok, pobrane i zainstalowane. 
Wygląda na to, że działa prawidłowo (chociaż na razie kilka zamówień).

**Comment by krystianbytom** [comment]
Mam dalej problem po aktualizacji do 1.6.1
Brak zmiany statusu, zamówienie nie jest widoczne

**Comment by emilleszczak2** [comment]
@krystianbytom Korzystasz z opcji tworzenia zamówienia przed czy po płatności ?
