### ISSUE TITLE
Wersja 1.6.1 nie tworzy zamówienia

### ISSUE THREAD

**Issue by Sasni** [pay-now/paynow-prestashop#108]
W module mam zaznaczone aby zamówienie tworzyło się "Po kliknięciu przycisku Złóż zamówienie" Robię więc testowe zamówienie, wybieram PayNow, przekierowuje mnie na stronę wyboru banków ale zamówienie w sklepie nie jest tworzone :/ 
Klientowi pobierane są środki z konta - bo dokonuje poprawnie płatności ale sklep nic o tym nie wie, Klient ma nawet dalej produkt w koszyku (który powinien się opróżnić po złożeniu zamówienia). 

Sprawdziłem - wersja 1.5.5 nie ma takiego problemu i zamówienia są tworzone poprawnie. 
Moja wersja Prestashop : 1.7.7.7

**Comment by emilleszczak2** [comment]
@Sasni Czy instalacja nowej wersji zakończyła się poprawnie?

**Comment by Sasni** [comment]
Zrobiłem instalację ponownie problem chyba rozwiązany. Coś się ewidentnie nie zapisało poprawie podczas pierwotnej aktualizacji. Można zamknąć...

**Comment by emilleszczak2** [comment]
@Sasni wystawiłem wersję 1.6.2 która powinna rozwiązać ewentualny problem braku konfiguracji.
