### ISSUE TITLE
Opis zamówienia:  Zamówienie do koszyka: xxxx

### ISSUE THREAD

**Issue by Wojciech-Poland** [pay-now/paynow-prestashop#114]
Witam,
Czy zamiast numeru koszyka jest możliwość aby był numer zamówienia??
![nrZamowienia](https://user-images.githubusercontent.com/8407470/150943309-72fb5f42-507d-4c48-ba30-4a09a6d02986.png)

**Comment by emilleszczak2** [comment]
Jeśli jest to model tworzenia zamówienia po udanej płatności to nie ma takiej możliwości. Jeśli zamówienie będzie tworzone przed płatnością to w tym miejscu pojawi się jego numer. Zmiany można dokonać w konfiguracji wtyczki.
