### ISSUE TITLE
Zwielokrotnione rekordy płatności

### ISSUE THREAD

**Issue by maciekwyka** [pay-now/paynow-prestashop#127]
Od którejś nowszej wersji wtyczki pojawił się problem polegający na tym że w zamówieniu klienta wpis o płatności występuje kilka razy, czasem dwa czasem trzy powtórzone rekordy w odstępach do kilku sekund.

Wersja PrestaShop: 1.7.8.2
Wersja wtyczki: 1.6.10

![Zrzut ekranu 2022-02-22 o 10 35 03](https://user-images.githubusercontent.com/12991339/155104631-731518a4-b4c9-4e1f-8104-5fa5e7cb77f8.png)
![Zrzut ekranu 2022-02-22 o 10 35 18](https://user-images.githubusercontent.com/12991339/155104651-6aaa01fd-de5f-493b-8c69-40d42f4d31bd.png)

**Comment by maciekwyka** [comment]
Konfiguracja modułu:
![Zrzut ekranu 2022-02-22 o 10 40 17](https://user-images.githubusercontent.com/12991339/155105203-5591adef-5ef8-4a84-9313-0fd4432ceee1.png)

**Comment by emilleszczak2** [comment]
@maciekwyka 
1. Jak były zmieniane statusy dla tego zamówienia?
2. Jak są ustawione statusy zamówień? Ile z nich ma ustawioną opcję "Zauważ czy zamówienie jest poprawne" ?

**Comment by maciekwyka** [comment]
Wygląda to tak ja na screenie, przy czym status "Przygotowanie w toku" został ręcznie ustawiony już po tym jak zwielokrotnione rekordy płatności się pojawiły.

![Zrzut ekranu 2022-02-23 o 14 30 49](https://user-images.githubusercontent.com/12991339/155329334-16a5881d-d8a9-4940-acb9-c6f8a3d739f6.png)

Konfiguracja statusów:

![Zrzut ekranu 2022-02-23 o 14 33 59](https://user-images.githubusercontent.com/12991339/155329757-fb719b1d-b907-419e-832c-816b2af8fccd.png)

![Zrzut ekranu 2022-02-23 o 14 34 20](https://user-images.githubusercontent.com/12991339/155329779-810dd3e6-67c7-46fe-949c-2d5b3b5ecf91.png)

**Comment by emilleszczak2** [comment]
Dzięki, w nowej wersji przywrócę to co było wcześniej, czyli aktualizację ID zamiast dodawania nowego.

**Comment by maciekwyka** [comment]
Po aktualizacji do 1.6.11 problem już nie występuje.
