### ISSUE TITLE
Undefined property: stdClass

### ISSUE THREAD

**Issue by WojciechLabas** [pay-now/paynow-prestashop#134]
Witam,
Od wersji 1.6.13 mam problem z stdClass
Wersja 1.6.14 pokazuje taki komunikat:
Notice w linii 538 w pliku /home/kf/public_html/modules/paynow/paynow.php
[8] Undefined property: stdClass::$tag_name

To tylko u mnie, czy ktoś jeszcze ma takie problem? 
Aktualnie wróciłem do modułu w wersji 1.6.12

**Comment by emilleszczak2** [comment]
@WojciechLabas Proponuję pobranie i instalację ponowną 1.6.14, zawiera zmiany które nie powinny generować tego komunikatu.

**Comment by WojciechLabas** [comment]
To pojawia mi się właśnie w wersji 1.6.14

Notice w linii 538 w pliku /home/kf/public_html/modules/paynow/paynow.php
[8] Undefined property: stdClass::$tag_name

**Comment by emilleszczak2** [comment]
Ja mam 1.6.14 zainstalowane w sklepie testowym i nie ma tego błędu.
Spróbuj podmienić warunek:
```php
if ($latest_release && isset($latest_release->tag_name) && version_compare($this->version, $latest_release->tag_name, '<')) {
...
}
```

**Comment by koltatiq** [comment]
Mam to samo od wczoraj, irytujące bo blokuje możliwość działania po stronie amina sklepu, na szczęście front dla klienta jest ok. wersja prestashop 1.7.8.5

**Comment by emilleszczak2** [comment]
@koltatiq próbwałeś dokonać tego fixa który dałem wyżej?

**Comment by koltatiq** [comment]
@emilleszczak2 Chyba sie na tym, aż tak nie znam, - nawet nie wiem, gdzie szukać tego pliku. Zainstalowałem wcześniejszą wersję wersję v1.6.13 i problem nie występuje - mnie to wystarcza :-) 
Dziwne, że nie mam belki "krzyczącej" że jest do pobrania nowa wersja, tym lepiej.

**Comment by emilleszczak2** [comment]
@koltatiq @WojciechLabas wydałem nową [wersję wtyczki](https://github.com/pay-now/paynow-prestashop/releases/tag/1.6.15) z poprawką

**Comment by koltatiq** [comment]
@emilleszczak2 , zauważyłem i już zainstalowałem, teraz działa jak należy. Dziękuję i pozdrawiam.

**Comment by WojciechLabas** [comment]
Wszystko działa, potwierdzam. Dziękuję
