### ISSUE TITLE
Uporczywa zmiana statusu płatności z anulowane na oczekuje płatności

### ISSUE THREAD

**Issue by koltatiq** [pay-now/paynow-prestashop#147]
Czy tylko ja mam taki problem? czy może to jakiś błąd konfiguracji. Przywraca zamówienie do statusu oczekuje na płatność mimo przeterminowanej płatności w panelu Paynow.
![2022-06-21](https://user-images.githubusercontent.com/82684133/174729077-bd824c0f-792c-4474-b40e-c8c08763a92c.png)
![2022-06-21-p](https://user-images.githubusercontent.com/82684133/174729082-fdc8bd0c-ebb7-4eeb-b947-4c5aa4b07a63.png)

**Comment by emilleszczak2** [comment]
@koltatiq podaj ID płatności, sprawdzimy czy to od nas przyszła informacja o zmianie statusu.

PS.
Nie jest to nic złego, dzięki temu że jest status oczekiwania na płatność można ją ponowić z poziomu sklepu.

**Comment by koltatiq** [comment]
mam ID transkacji, może to to: GO2O-ATY-E6W-E9D

Tylko wiesz, mając w sklepie stan magazynowy i sprzedaż wielekanałową, to anulując zamówienie przywracam produkt do ponownej sprzedaży, w momencie gdy zostanie kupiony gdzie indziej, następuje brak przy ponownej próbie zapłaty. Myślałem że jak mam ustawioną opcję **Użyj czasu ważności płatności** max 24h - to klient nie będzie już miał opcji ponownej zapłaty.

**Comment by emilleszczak2** [comment]
@koltatiq 
W konfiguracji wtyczki możesz ustawić inny status w sklepie - Anulowana dla powiadomienia o zmianie statusu płatności z Paynow - Czas ważności płatności wygasł
![Screenshot 2022-06-21 at 15 22 46](https://user-images.githubusercontent.com/2837751/174809841-df509b00-cd1a-4115-9c93-5ee370a9d147.png)
