### ISSUE TITLE
Automatyczne scrollowanie do payment_method - The Checkout

### ISSUE THREAD

**Issue by przemekkozlowski** [pay-now/paynow-prestashop#150]
cześć,
problem polega na tym, że gdy mam włączony moduł PayNow, to na stronie checkoutowej, strona automatycznie łapie anchor na sekcję z metodami płatności i jest automatyczny scroll.
Debugger na froncie wskazuje na wywoływanie się błędu "proszę wybrać metodę płatności".

Prestashop 1.7.8.6
Moduł do checkoutu: The Checkout od Presta Smart (https://prestasmart.com/en/20-the-checkout.html)
Theme: Warehouse

**Comment by emilleszczak2** [comment]
Moduł paynow sam z siebie nie scrolluje strony robi to the checkout. Należy zweryfikować jaki fragment js w The Checkout jest za to odpowiedzialny. Możliwe że The Checkout wyszukuje w stronie jakiegoś elementu który znajduje w    metodzie płatności i do nie scrolluje. Może to być elementu do prezentacji błedów lub jakiś inny element.

**Comment by przemekkozlowski** [comment]
jakby ktoś szukał hotfixa to:

`modules/paynow/views/js/front.js`
i należy zakomentować linię
`$('#paynow_blik_code').focus();`
