### ISSUE TITLE
problem z zainstalowaniem nowej wersji

### ISSUE THREAD

**Issue by AndrzejSzczepanik** [pay-now/paynow-prestashop#151]
Instaluję i nic, wersja pozostaje stara 1.6.18 chociaż proces ładowania modułu przebiega poprawnie, myślałem że może to jakiś problem z cachem, wyczyśliłem, także z cachu hostingodawcy i nic , dlaej to samo, ma ktoś jakąś podpowieź w czym twki problem?

**Comment by AndrzejSzczepanik** [comment]
presta 1.7.8.5 obydwa sklepu, jeden mulilanguage i multicurrency

**Comment by emilleszczak2** [comment]
Nie została poprawnie podbita wersja w pliku paynow.php przez co nie zmienia się wersja w sklepie. Zostanie wydana poprawiona wersja wtyczki.

**Comment by AndrzejSzczepanik** [comment]
ostatni jakoś łaty , łat coraz cześciej wychodzą, zamiast rzadziej ale stabilniej

**Comment by DeveloperMovecloser** [comment]
@AndrzejSzczepanik 
Poprawiliśmy oznaczenie wersji (zarówno na głównym branchu jak i na paczce release. 
Spróbuj proszę ponownie.
