### ISSUE TITLE
problem z odblokowaniem przycisku ZAMÓWIENIE Z OBOWIĄZKIEM ZAPŁATY

### ISSUE THREAD

**Issue by Sebik197821** [pay-now/paynow-prestashop#160]
Po aktualizacji do najnowszej wersji nagle zmalała mi ilość zamówień. Zainteresowałem się tematem i wyszło mi coś takiego. W trakcie składania zamówienia wszystko idzie dobrze do momentu wybrania sposobu płatności. Wybieram płatność PayNow następnie akceptuję warunki regulaminu i ... przycisk finalizacji zamówienia pozostaje "wyszarzony". Co prawda działa po kliknięciu, ale klientów wprowadza w błąd. Po najechaniu na niego pokazuje się ikonka nieaktywnego przycisku, szary przycisk. Sytuacja zmienia się w momencie ponownego użycia wyboru banku - wystarczy przełączyć z np. wybranego ING na inny i z powrotem. Jednak klienci tego nie wyłapują i jest problem z zamówieniami. Proszę o przesłanie rozwiązania do tego problemu ( w poprzedniej wersji ten problem nie występował.
Adres sklepu: www.szachysklep.com.pl
PHP 7.4, 
Prestashop 1.7.7.5

**Comment by krzysztofustowski** [comment]
[Sebik197821](https://github.com/Sebik197821) Wydaliśmy poprawkę, wersję 1.6.22 która poprawia ten błąd. 
Dzięki za zgłoszenie.

**Comment by Sebik197821** [comment]
Dziękuję bardzo za naniesienie poprawki, obecnie moduł działa prawidłowo 😊

 

Z poważaniem

Sebastian Tarach
Marketing Manager



A: 59-100 Polkowice, ul. Dąbrowskiego 29

T: +48 601 420 975

E:  ***@***.***> ***@***.***

W:  <http://www.hurtowniastepien.pl/> www.hurtowniastepien.pl

F: fb.pl/HurtowniaStepienPolkowice

N: 692-23-37-202 
KRS: 0000230163
BDO: 000491641
