### ISSUE TITLE
nazwa folderu

### ISSUE THREAD

**Issue by kamzerinho** [pay-now/paynow-prestashop#164]
jakby ktoś się zastanawiał czemu nie aktualizuje mu modułu do najnowszej wersji od zaplecza presta, należy w zipie zmienić nazwe folderu z paynow-prestashop-1.6.23 na paynow i powinno zadziałać

**Comment by emilleszczak2** [comment]
@kamzerinho Był błąd w przygotowaniu paczki zip. Pobierz ponownie plik z aktualizacją: https://github.com/pay-now/paynow-prestashop/releases/download/1.6.23/paynow.zip
