### ISSUE TITLE
upgrade do 1.6.23

### ISSUE THREAD

**Issue by Cezary-sp7ukl** [pay-now/paynow-prestashop#165]
podczas próby aktualizacji wyskakuje:

Ups... Przesyłanie nie powiodło się.
Plik pobrany kilka razy i kilka prób zainstalowania - za każdym razem to samo.

Poza tym plik ma prawie 1MB więcej niż poprzednia wersja.

**Comment by krzysztofustowski** [comment]
@Cezary-sp7ukl poprawiliśmy artefakty releasu - to powinno pomóc. Ponów proszę próbę i daj znać czy pomogło.

**Comment by krzysztofustowski** [comment]
Jeśli aktualizujesz ręcznie na bazie pliku releasowego - pobierz proszę plik paynow.zip.

**Comment by Cezary-sp7ukl** [comment]
Ok - to jak to aktualizować jak wszystkie inne moduły?

 

Pozdrawiam

mgr inż. (MSc) Cezary T. Libert (CEO) , MCP

HamRadioShop 

Autoryzowany Dystrybutor radiotelefonów AnyTone, TYT, Zastone, Baofeng w Polsce

NIP (VAT ID): PL7251200243        REGON: 473275532        GIOŚ: E0015945WBW        Nr rejestrowy BDO: 000006232

Przedsiębiorca Telekomunikacyjny – nr rej. UKE: 10733

HamRadioShop
tel. +48 602 675 847

sp7ukl ex sp2ukl

**Comment by krzysztofustowski** [comment]
Tak, tak jak każdy inny moduł.  Należy pobrać paczkę ZIP (https://github.com/pay-now/paynow-prestashop/releases/download/1.6.23/paynow.zip) i ten plik należy wgrać w Panelu w Menedżerze modułów.

**Comment by Cezary-sp7ukl** [comment]
O wiem, myślałem że jest sposób na aktualizację z poziomu presty

 

Pozdrawiam

mgr inż. (MSc) Cezary T. Libert (CEO) , MCP

HamRadioShop 

Autoryzowany Dystrybutor radiotelefonów AnyTone, TYT, Zastone, Baofeng w Polsce

NIP (VAT ID): PL7251200243        REGON: 473275532        GIOŚ: E0015945WBW        Nr rejestrowy BDO: 000006232

Przedsiębiorca Telekomunikacyjny – nr rej. UKE: 10733

HamRadioShop
tel. +48 602 675 847

sp7ukl ex sp2ukl
