### ISSUE TITLE
Logotypy banków są źle wyświetlane

### ISSUE THREAD

**Issue by maciekwyka** [pay-now/paynow-prestashop#166]
Proszę o poprawienie wyświetlania logotypów banków, aktualnie loga banków VELO i Nest! są za duże, wychodzą poza obrys przycisku, z kolei np. logotyp "Bank Nowy BFG" jest rozmyty, niskiej rozdzielczości.

Proszę poprawić aby wszystkie logotypy były aktualne, odpowiedniej wielkości oraz w jakości odpowiedniej dla ekranów Retina.

<img width="751" alt="Zrzut ekranu 2023-02-13 o 15 33 38" src="https://user-images.githubusercontent.com/12991339/218487162-f5856903-c124-4596-ac58-d7911bdef6f6.png">

**Comment by emilleszczak2** [comment]
@maciekwyka możesz podrzucić adres sklepu w celu weryfikacji?

**Comment by maciekwyka** [comment]
No mogę, ale sprawdzam właśnie i tak jest na wszystkich sklepach które używają wtyczki paynow :)

**Comment by maciekwyka** [comment]
Tutaj oficjalny logotyp Nest Bank:
https://nestbank.prowly.com/presskits/logotypy-nest-banku

Aktualne logo Bank Nowy S.A.
https://www.banknowy.pl/images/modules/logo_mini.png

**Comment by emilleszczak2** [comment]
@maciekwyka dzięki, poprawimy ikonki

**Comment by maciekwyka** [comment]
No myślę że najlepiej by było zrobić wszystkie ikonki w rozmiarze np. 200x120, we wtyczce wyświetlać je na 50% (retina).
Stara wtyczka mogła by zostać jak jest a nowa czerpała by obrazki z nowego źródła, zamiast https://static.paynow.pl/payment-method-icons/1000.png było by np. https://static.paynow.pl/payment-method-icons/1000@2.png

**Comment by emilleszczak2** [comment]
@maciekwyka ikonki poprawione

**Comment by maciekwyka** [comment]
@emilleszczak2 Nest i Bank Nowy istotnie poprawione, ale z VELO nadal jakiś problem
<img width="702" alt="Zrzut ekranu 2023-02-14 o 13 55 22" src="https://user-images.githubusercontent.com/12991339/218745298-6c9073a7-bd87-4c33-9492-28ba8d8c0b56.png">

**Comment by emilleszczak2** [comment]
Dla velo niestety będziemy musieli przygotować poprawkę we wtyczce aby lepiej skalować ikonki.

**Comment by emilleszczak2** [comment]
@maciekwyka W najnowszej wersji 1.6.26 została zrealizowana poprawka na skalowanie Velo.

**Comment by emilleszczak2** [comment]
@maciekwyka Poprawka w wersji wtyczki: 1.6.26

**Comment by maciekwyka** [comment]
Tak, potwierdzam, teraz jest OK, jedyne moje życzenie teraz to płatność kartą w modelu white label :)

**Comment by maciekwyka** [comment]
i Apple Pay
