### ISSUE TITLE
Zmiana sposobu informowania o nowej wersji wtyczki

### ISSUE THREAD

**Issue by maciekwyka** [pay-now/paynow-prestashop#167]
Aktualnie jak jest nowa wersja wtyczki to moduł wyświetla duży żółty baner z tą informacją na praktycznie każdej stronie Back Office. Proponuję aby to zmienić na bardziej standardowe zachowanie, to jest poprzez wbudowany mechanizm PrestaShop (Moduły -> Menedżer modułów -> Aktualizacje)

W chwili obecnej jak jest nowa wersja wtyczki ale jej jeszcze nie zaktualizujemy a pracujemy w Back Office, to ten duży żółty baner przeszkadza.

**Comment by emilleszczak2** [comment]
To jest celowe zachowanie. Prestashop informuje jedynie o aktualizacjach dla modułów kupionych przez ich market, pozostałe nie mają wsparcia. Jeśli to przeszkadza Wam w pracy a nie chcecie aktualizować modułu proponuję usunąć sobie hook podpięty dla modułu displayAdminAfterHeader.
