### ISSUE TITLE
Płatności kartą w modelu White label

### ISSUE THREAD

**Issue by maciekwyka** [pay-now/paynow-prestashop#176]
Czy wtyczka PayNow dla PrestaShop obsługuje płatności kartą w modelu WhiteLabel tak jak jest to w przypadku BLIK?

**Comment by emilleszczak2** [comment]
Na ten moment nie ma takiej możliwości.

**Comment by maciekwyka** [comment]
Jest szansa że się to pojawi?

**Comment by emilleszczak2** [comment]
Na ten moment w paynow nie ma takiej usługi i nie ma jej w najbliższych planach.
