### ISSUE TITLE
Zła cena produktu w historii zamówienia w BO i FO w przypadku sklepu wielowalutowego

### ISSUE THREAD

**Issue by benitko** [pay-now/paynow-prestashop#182]
**Wstęp:**
Wersja modułu Paynow: **v1.6.24**
Wersja Prestashop: **1.7.8.8**

W sklepie mam włączoną obsługę trzech walut: PLN, EUR i USD.
Waluta domyślna ustawiona w sekcji "Międzynarodowy > Lokalizacja" to PLN.
Ceny produktów w EUR i USD ustawiane są przy pomocy funkcji "Wycena > Specyficzne ceny" w formularzu edycji produktu.

**Opis problemu:**
W przypadku zamówień złożonych w walucie PLN z płatnością przez Paynow, wyświetlana jest niepoprawna cena przy poszczególnych produktach na liście produktów w zamówieniu - zarówno w back office (w szczegółach zamówienia w zakładce "Sprzedaż > Zamówienia"), jak i na stronie śledzenia zamówienia dla klienta w front office.

Pola z sumą wartości zamówienia, kosztem dostawy, wartością podatku za całe zamówienie, itd., są wyświetlane poprawnie. Błąd jest jedynie w cenach wyświetlanych przy produktach w zamówieniu.

Taki błąd uniemożliwia chociażby automatyczne wystawianie faktur za pośrednictwem zewnętrznego oprogramowania, ponieważ nie ma możliwości pobrania prawidłowej ceny, nie mówiąc o wprowadzaniu niepotrzebnego zamieszania dla pracowników oraz klienta.

Błędna cena produktów może mieć związek z cenami ustawianymi przy pomocy funkcji "Specyficzne ceny", ponieważ w przypadku produktu ze screena wyświetlana jego cena w walucie EUR (ale z symbolem PLN zamiast EUR), ustawiona przy pomocy tej funkcji. 

![obraz](https://github.com/pay-now/paynow-prestashop/assets/23700888/0f2f3249-3eaf-49a3-906e-355f9b4ce5dc)

![obraz](https://github.com/pay-now/paynow-prestashop/assets/23700888/f2920eeb-abc5-4293-8018-1d6dff193a6c)

![obraz](https://github.com/pay-now/paynow-prestashop/assets/23700888/f23417e5-73d0-419f-9017-2198081c230d)

![obraz](https://github.com/pay-now/paynow-prestashop/assets/23700888/a8b1f131-8b62-4c7f-9e84-6b611d3ec2fb)

Wszystkie ceny wyświetlane w mailu z potwierdzeniem zamówienia wysyłanym do klienta są prawidłowe.

![obraz](https://github.com/pay-now/paynow-prestashop/assets/23700888/e6cefdcd-34e3-47ac-a54f-4663d107efa8)

Problem występuje jedynie z modułem Paynow. Pozostałe moduły do płatności, czy to w PLN, czy w innych walutach, działają prawidłowo. Bardzo proszę o interwencję, ponieważ problem występował od zawsze w każdej z wersji modułu Paynow na Prestashop w wersji 1.7+.

**Comment by emilleszczak2** [comment]
@benitko Konfiguracja wtyczki jest ustawiona na tworzenie zamówienia po płatności czy przed ?

**Comment by benitko** [comment]
> @benitko Konfiguracja wtyczki jest ustawiona na tworzenie zamówienia po płatności czy przed ?

Zapomniałem wspomnieć - ustawione jest tworzenie zamówienia po udanej płatności.

**Comment by e-com-presta** [comment]
Prestashop to nie jest aplikacja sklepu internetowego, tylko typowy wirus.
W silniku tego programistycznego gniota są procedury fałszujące wartość sprzedaży dla produktów z rabatami:
https://prestademo.eu.org/pl/content/6-testy-prestashop-17

**Comment by benitko** [comment]
@emilleszczak2 Czy błąd zostanie kiedykolwiek naprawiony?

**Comment by benitko** [comment]
Rozwiązałem już z Państwem umowę, można zamknąć.
