### ISSUE TITLE
Adresy Powiadomień i Powrotu

### ISSUE THREAD

**Issue by lukash881** [pay-now/paynow-prestashop#21]
Czy adres Powiadomień: https://twoja-domena.pl/module/paynow/notifications  jest poprawny?
Zamówienie nie jest oznaczane jako opłacone.

**Comment by emilleszczak2** [comment]
@lukash881 Tak, jeśli masz jakiś problem to proszę napisz na support@paynow.pl

**Comment by ggfunnn** [comment]
Mam dokładnie ten sam problem. Proszę o rozwiązanie.
