### ISSUE TITLE
Po aktualizacji do 1.7.9 nie ma Blik-a

### ISSUE THREAD

**Issue by maciekwyka** [pay-now/paynow-prestashop#216]
Po aktualizacji modułu z 1.7.8 do 1.7.9 klient nie ma dostępnej metody płatności Blik

**Comment by paynow-support** [comment]
Dzień dobry,

dziękujemy za wiadomość.

Informujemy, że problem z płatnościami BLIK nie jest spowodowany aktualizacją pluginu do najnowszej wersji 1.7.9. Problem z płatnościami BLIK jest spowodowany globalną awarią BLIK, która rozpoczęła się przed godziną 16.

Aktualnie operator płatności BLIK pracuje nad przywróceniem możliwości płatności przy pomocy tej metody płatności.

Skala awarii jest wysoka, dlatego na jej czas wyłączyliśmy możliwość wyboru BLIK przez kupujących. Kierujemy ich na działające metody płatności. Pozostałe metody płatności działają bez problemu.

Po ustaniu awarii wrócimy z oficjalną komunikacją mailową w tej sprawie.

Pozdrawiam
Zespół Paynow
