### ISSUE TITLE
Błąd w paczce.

### ISSUE THREAD

**Issue by prestamod** [pay-now/paynow-prestashop#36]
include_once(dirname(__FILE__) . '/vendor/autoload.php');
include_once(dirname(__FILE__) . '/classes/PaynowLogger.php');

Tak się składa, że nie ma pliku vendor/autoload.pphp

**Comment by emilleszczak2** [comment]
@prestamod Czy pobrałeś plik `paynow.zip` z przygotowaną wersją wtyczki ? ?

**Comment by prestamod** [comment]
Zobacz proszę do kodu poniżej aktualny plik. 

**Zobacz również do katalogów na github: brakuje vendor/autoload.php**


<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License (MIT)
 * that is bundled with this package in the file LICENSE.md.
 *
 * @author mElements S.A.
 * @copyright mElements S.A.
 * @license   MIT License
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

include_once(dirname(__FILE__) . '/vendor/autoload.php');
include_once(dirname(__FILE__) . '/classes/PaynowLogger.php');

**Comment by prestamod** [comment]
* NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License (MIT)
 * that is bundled with this package in the file LICENSE.md.
 *
 * @author mElements S.A.
 * @copyright mElements S.A.
 * @license   MIT License
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

include_once(dirname(__FILE__) . '/vendor/autoload.php');
include_once(dirname(__FILE__) . '/classes/PaynowLogger.php');

**Comment by emilleszczak2** [comment]
Pliki są dokładane w trakcie build'a wtyczki z composera. W repozytorium znajduje się wersja developerska.
