### ISSUE TITLE
Automatyczne tworzenie i wysyłka linku do płatności

### ISSUE THREAD

**Issue by krasnaldev** [pay-now/paynow-prestashop#37]
Czy jest możliwość, żeby moduł wysyłał do klienta maila z linkiem do płatności od razu po utworzeniu zamówienia? Jeśli klient wybrał sposób płatności (na przykład mbank) i w międzyczasie z jakiegoś powodu opuści stronę banku to utraci możliwość dokończenia tej transakcji. Wchodząc w powiadomienie na mailu otrzyma tylko link do śledzenia statusu ale nie będzie mógł ponowić płatności. Zależy nam na takiej funkcjonalności, aby klient od razu po złożeniu zamówienia dostawał link na maila i w każdej chwili mógł ją opłacić, nawet gdy przydarzą mu się kłopoty techniczne.

**Comment by emilleszczak2** [comment]
@krasnaldev Dziękujemy za propozycję udoskonalenia wtyczki, rozważymy jej wprowadzenie.

**Comment by javasurf** [comment]
> Czy jest możliwość, żeby moduł wysyłał do klienta maila z linkiem do płatności od razu po utworzeniu zamówienia? Jeśli klient wybrał sposób płatności (na przykład mbank) i w międzyczasie z jakiegoś powodu opuści stronę banku to utraci możliwość dokończenia tej transakcji. Wchodząc w powiadomienie na mailu otrzyma tylko link do śledzenia statusu ale nie będzie mógł ponowić płatności. Zależy nam na takiej funkcjonalności, aby klient od razu po złożeniu zamówienia dostawał link na maila i w każdej chwili mógł ją opłacić, nawet gdy przydarzą mu się kłopoty techniczne.

Dobry pomysl. Popieram!

**Comment by emilleszczak2** [comment]
@javasurf Zamawiający otrzymuje już maila o rozpoczęciu transakcji z systemu Paynow w którym jest link. Jaki jest sens wysyłania kolejnego maila?

**Comment by krasnaldev** [comment]
Kupujący otrzymuje link, w którym może sobie sprawdzić status transakcji. Jeśli transakcja się nie powiodła to w żaden sposób nie może jej ponowić. Sens jest taki, żeby jednak mógł ją ponowić.

Obsługa sklepu powinna w każdej chwili mieć możliwość wygenerowania nowego linku dla klienta jeśli zadzwoni, lub skontaktuje się mailowo. Klient powinien mieć też w każdej chwili możliwość rozpoczęcia płatności na nowo, nawet jeśli nie ma konta na sklepie. Jest to podstawowa funkcjonalność, która pozwala zmniejszyć ilość nieopłaconych zamówień.

**Comment by emilleszczak2** [comment]
@krasnaldev Zgadza się link jest do statusu płatności, jeśli jej nie rozpoczał może to zrobić.
Jeśli chodzi po ponowną płatność do zamówienia to jest to standardowo możliwe z poziomu szczegółów zamówienia.
Inną kwestią jest kontynuowanie płatności która się nie udało o której piszesz.
Sprawdzimy możliwość dodania funkcjonalności dla obsługi sklepu aby wygenerować nowy link do płatności i wysłać go mailem.

**Comment by krasnaldev** [comment]
Tak, tylko 90% klientów nie rejestruje kont w sklepach internetowych więc jak mają wejść w szczegóły zamówienia? Tak naprawdę idealnym rozwiązaniem by było gdyby klient nawet po rozpoczęciu płatności mógł z poziomu tego linka z maila, który już jest wysyłany, ponowić płatność (bez konieczności wysyłania następnego). Natomiast skoro system jest tak skonstruowany to trzeba ten problem rozwiązać z poziomu modułu.

**Comment by emilleszczak2** [comment]
Historia zamówień była zawsze dostępna dla zalogowanych jak i nie zalogowanych. Dla gości przez podanie numeru zamówienia i e-maila.

**Comment by krasnaldev** [comment]
To wszystko pięknie brzmi w teorii. Gdyby jeszcze tylko klient o tym wiedział. Proces dokonania zakupu i opłaty musi być jak najbardziej prosty i dogodny dla klienta, inaczej powstają problemy. Jeśli klientowi nie udało się opłacić przez link i nie może ponowić płatności, to nie będzie szukał informacji gdzie i jak ma się zalogować. Po prostu pójdzie gdzie indziej albo zrezygnuje całkowicie. Dlatego utworzyłem tę sprawę. Natomiast i tak testujemy już rozwiązanie innej firmy więc jeśli Państwo nie chcecie wprowadzić takiej funkcjonalności to zamykam temat, bo nie ma nad czym dalej dyskutować. Moim zdaniem jest to niezbędne.

**Comment by emilleszczak2** [comment]
@krasnaldev zaproponowałem powyżej jakie rozwiązania mamy na ten moment, nad Twoim pomysłem się zastanowimy.
