### ISSUE TITLE
Pomimo zaakceptowanej płatności, status zamówienia to oczekuje na płatność

### ISSUE THREAD

**Issue by JaqubR** [pay-now/paynow-prestashop#68]

**Comment by emilleszczak2** [comment]
@JaqubR Czy poprawnie skonfigurowałeś adres powiadomień ? Patrz https://github.com/pay-now/paynow-prestashop#faq

**Comment by JaqubR** [comment]
@emilleszczak2 Tak, adres powiadomień i powrotu są poprawnie skonfigurowane.

**Comment by JaqubR** [comment]
Czy brak aktualizacji statusu może być spowodowany przerwą techniczną w sklepie?

**Comment by emilleszczak2** [comment]
Podaj adres sklepu sprawdzimy czy powiadomienia poprawnie dochodzą do sklepu.
Możesz również sprawdzić logi wtyczki w swoim sklepie.

**Comment by JaqubR** [comment]
https://prohorse.pl/

**Comment by JaqubR** [comment]
Już wszystko działa, problem był chyba spowodowany przez przerwę techniczną - webhook nie mógł uzyskać odpowiedzi.
