### ISSUE TITLE
Paynow rev 1.5.x prestashop

### ISSUE THREAD

**Issue by JacekBakowskiEMV** [pay-now/paynow-prestashop#97]
CRITICAL 18:20:57 	request 	Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Cannot declare class LinkHelper, because the name is already in use" at /home/klient.dhosting.pl/........./public_html/modules/paynow/classes/LinkHelper.php line 13

Moduł instaluje się z błędem i wywala cały sklep , na debugu efekt powyższy.

Usuniecie ręczne modułu przez FTP i zainstalowanie wersji 1.4 przywraca funkcjonalność.

**Comment by emilleszczak2** [comment]
@JacekBakowskiEMV Jaki moduł konfliktuje w nazwie klasy?

**Comment by JacekBakowskiEMV** [comment]
Mam tylko taki błąd złapany: 
PHP Fatal error:  Cannot declare class LinkHelper, because the name is already in use in /home/klient.dhosting.pl/.../.../public_html/modules/paynow/classes/LinkHelper.php on line 13

**Comment by emilleszczak2** [comment]
Korzystasz z MailerLite lub MailChimp?

**Comment by JacekBakowskiEMV** [comment]
Tak MailChimp.

**Comment by emilleszczak2** [comment]
Dzięki, zweryfikujemy to i dokonamy zmian.

**Comment by JacekBakowskiEMV** [comment]
Dzięki. Czekam na update :)

**Comment by emilleszczak2** [comment]
@JacekBakowskiEMV wydałem nową, poprawioną wersję https://github.com/pay-now/paynow-prestashop/releases/tag/1.5.3

**Comment by JacekBakowskiEMV** [comment]
Dzięki za szybką interwencję, działa.
ps. przy włączonym trybie Wyświetl metody płatności gdzie pokazuje się BLIK znika przycisk akceptacji zamówienia sklepu "Kupuje i Płacę" co trochę wprowadza w błąd bo ten przycisk jest na końcu podsumowania zamówienia. Jak był do wyboru osobno BLIK i przelewy bez opcji wpisania to było lepiej.

**Comment by emilleszczak2** [comment]
@JacekBakowskiEMV to celowy zabieg, aby móc przeprocesować płatność BLIK bez przekierowania użytkownika na inną stronę formularzem.
Jeśli nie chcesz mieć w swoim sklepie dostępnego modelu White Label napisz proszę taką prośbę na nasz support.

**Comment by Wojciech-Poland** [comment]
> Mam tylko taki błąd złapany: PHP Fatal error: Cannot declare class LinkHelper, because the name is already in use in /home/klient.dhosting.pl/.../.../public_html/modules/paynow/classes/LinkHelper.php on line 13

Mam to samo, ale błąd powoduje inny moduł. Wg developera tamtego modułu, płatność powinna się instalować bez problemu, pomimo że klasa LinkHelper jest wykorzystywana.

Wersję modułu 1.5.x instalować będę w styczniu, bo teraz nie walczyć z awarią sklepu przez płatności.

**Comment by emilleszczak2** [comment]
@Wojciech-Poland Wersja 1.5.3 jest pozbawiona konfliktu z innymi wtyczkami. Był to błąd niezależny, nie jesteśmy w stanie zweryfikować wszystkich dostępnych na rynku wtyczek.

**Comment by Wojciech-Poland** [comment]
> @Wojciech-Poland Wersja 1.5.3 jest pozbawiona konfliktu z innymi wtyczkami. Był to błąd niezależny, nie jesteśmy w stanie zweryfikować wszystkich dostępnych na rynku wtyczek.

Oczywiście, rozumiem to. Chodziło mi bardziej o informację, że to nie ten jeden moduł powoduje.
Zaryzykowałem i się udało. Wersja 1.5.3 instaluje się prawidłowo i działa prawidłowo.
Dziękuję
